// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCGDDyibFhz4KWW9OFEUgikPL1JWuo2Zj4",
    authDomain: "ploter-3bc40.firebaseapp.com",
    databaseURL: "https://ploter-3bc40-default-rtdb.firebaseio.com",
    projectId: "ploter-3bc40",
    storageBucket: "ploter-3bc40.firebasestorage.app",
    messagingSenderId: "479945257157",
    appId: "1:479945257157:web:1faf202b879bef1298c0ac",
    measurementId: "G-MWT2KKY28H",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDDyibFhz4KWW9OFEUgikPL1JWuo2Zj4',
    appId: "1:479945257157:web:1faf202b879bef1298c0ac",
    messagingSenderId: '479945257157',
    projectId: 'ploter-3bc40',
    databaseURL: "https://ploter-3bc40-default-rtdb.firebaseio.com",
    storageBucket: 'ploter-3bc40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGDDyibFhz4KWW9OFEUgikPL1JWuo2Zj4',
    appId: '1:479945257157:ios:1faf202b879bef1298c0ac',
    messagingSenderId: '479945257157',
    projectId: 'ploter-3bc40',
    databaseURL: "https://ploter-3bc40-default-rtdb.firebaseio.com",
    storageBucket: 'ploter-3bc40.firebasestorage.app',
    iosClientId:
        '479945257157-v9j162r12345vbp1fvs0c0d1tglph3i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ploter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGDDyibFhz4KWW9OFEUgikPL1JWuo2Zj4',
    appId: '1:479945257157:ios:1faf202b879bef1298c0ac',
    messagingSenderId: '479945257157',
    projectId: 'ploter-3bc40',
    databaseURL: "https://ploter-3bc40-default-rtdb.firebaseio.com",
    storageBucket: 'ploter-3bc40.firebasestorage.app',
    iosClientId:
        '479945257157-v9j162r12345vbp1fvs0c0d1tglph3i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ploter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGDDyibFhz4KWW9OFEUgikPL1JWuo2Zj4',
    appId: '1:479945257157:web:1faf202b879bef1298c0ac',
    messagingSenderId: '479945257157',
    projectId: 'ploter-3bc40',
    databaseURL: "https://ploter-3bc40-default-rtdb.firebaseio.com",
    storageBucket: 'ploter-3bc40.firebasestorage.app',
    measurementId: 'G-MWT2KKY28H',
  );
}
